BEGIN;

INSERT INTO checklist_legado_importacao (
  municipio, uf, ano, mes, atividade, status_origem, data_conclusao, observacoes
)
VALUES
  ('Jurema', 'PE', 2026, 1, 'Monitorar a alimentação do sistema pelo cliente, verificando possível ausência ou má alimentação.', 'Concluído', '2026-01-31', NULL),
  ('Jurema', 'PE', 2026, 1, 'Verificar se os clientes utilizam os principais recursos e benefícios do sistema do módulo atuante.', 'Concluído', '2026-01-31', NULL),
  ('Jurema', 'PE', 2026, 1, 'Acompanhar as integrações, quando aplicável.', 'Concluído', '2026-01-31', NULL),
  ('Jurema', 'PE', 2026, 1, 'Monitorar a necessidade de treinamentos e atualizações.', 'Concluído', '2026-01-31', NULL),
  ('Jurema', 'PE', 2026, 1, 'Informar ao cliente sobre as principais implementações do módulo.', 'Concluído', '2026-01-31', NULL),
  ('Jurema', 'PE', 2026, 1, 'Acompanhar e gerenciar as demandas de programação e/ou técnicas.', 'Concluído', '2026-01-31', NULL),
  ('Jurema', 'PE', 2026, 1, 'No portal da transparência, acompanhar mensalmente as pendências, encaminhá-las ao responsável e enviar o Integra por e-mail.', 'Concluído', '2026-01-31', NULL),
  ('Jurema', 'PE', 2026, 2, 'Monitorar a alimentação do sistema pelo cliente, verificando possível ausência ou má alimentação.', 'Concluído', '2026-02-28', NULL),
  ('Jurema', 'PE', 2026, 2, 'Verificar se os clientes utilizam os principais recursos e benefícios do sistema do módulo atuante.', 'Concluído', '2026-02-28', NULL),
  ('Jurema', 'PE', 2026, 2, 'Acompanhar as integrações, quando aplicável.', 'Concluído', '2026-02-28', NULL),
  ('Jurema', 'PE', 2026, 2, 'Monitorar a necessidade de treinamentos e atualizações.', 'Concluído', '2026-02-28', NULL),
  ('Jurema', 'PE', 2026, 2, 'Informar ao cliente sobre as principais implementações do módulo.', 'Concluído', '2026-02-28', NULL),
  ('Jurema', 'PE', 2026, 2, 'Acompanhar e gerenciar as demandas de programação e/ou técnicas.', 'Concluído', '2026-02-28', NULL),
  ('Jurema', 'PE', 2026, 2, 'No portal da transparência, acompanhar mensalmente as pendências, encaminhá-las ao responsável e enviar o Integra por e-mail.', 'Concluído', '2026-02-28', NULL),
  ('Jurema', 'PE', 2026, 3, 'Monitorar a alimentação do sistema pelo cliente, verificando possível ausência ou má alimentação.', 'Concluído', '2026-03-31', NULL),
  ('Jurema', 'PE', 2026, 3, 'Verificar se os clientes utilizam os principais recursos e benefícios do sistema do módulo atuante.', 'Concluído', '2026-03-31', NULL),
  ('Jurema', 'PE', 2026, 3, 'Acompanhar as integrações, quando aplicável.', 'Concluído', '2026-03-31', NULL),
  ('Jurema', 'PE', 2026, 3, 'Monitorar a necessidade de treinamentos e atualizações.', 'Concluído', '2026-03-31', NULL),
  ('Jurema', 'PE', 2026, 3, 'Informar ao cliente sobre as principais implementações do módulo.', 'Concluído', '2026-03-31', NULL),
  ('Jurema', 'PE', 2026, 3, 'Acompanhar e gerenciar as demandas de programação e/ou técnicas.', 'Concluído', '2026-03-31', NULL),
  ('Jurema', 'PE', 2026, 3, 'No portal da transparência, acompanhar mensalmente as pendências, encaminhá-las ao responsável e enviar o Integra por e-mail.', 'Concluído', '2026-03-31', NULL),
  ('Jurema', 'PE', 2026, 4, 'Monitorar a alimentação do sistema pelo cliente, verificando possível ausência ou má alimentação.', 'Concluído', '2026-04-30', NULL),
  ('Jurema', 'PE', 2026, 4, 'Verificar se os clientes utilizam os principais recursos e benefícios do sistema do módulo atuante.', 'Concluído', '2026-04-30', NULL),
  ('Jurema', 'PE', 2026, 4, 'Acompanhar as integrações, quando aplicável.', 'Concluído', '2026-04-30', NULL),
  ('Jurema', 'PE', 2026, 4, 'Monitorar a necessidade de treinamentos e atualizações.', 'Concluído', '2026-04-30', NULL),
  ('Jurema', 'PE', 2026, 4, 'Informar ao cliente sobre as principais implementações do módulo.', 'Concluído', '2026-04-30', NULL),
  ('Jurema', 'PE', 2026, 4, 'Acompanhar e gerenciar as demandas de programação e/ou técnicas.', 'Concluído', '2026-04-30', NULL),
  ('Jurema', 'PE', 2026, 4, 'No portal da transparência, acompanhar mensalmente as pendências, encaminhá-las ao responsável e enviar o Integra por e-mail.', 'Concluído', '2026-04-30', NULL),
  ('Jurema', 'PE', 2026, 5, 'Monitorar a alimentação do sistema pelo cliente, verificando possível ausência ou má alimentação.', 'Concluído', '2026-05-31', NULL),
  ('Jurema', 'PE', 2026, 5, 'Verificar se os clientes utilizam os principais recursos e benefícios do sistema do módulo atuante.', 'Concluído', '2026-05-31', NULL),
  ('Jurema', 'PE', 2026, 5, 'Acompanhar as integrações, quando aplicável.', 'Concluído', '2026-05-31', NULL),
  ('Jurema', 'PE', 2026, 5, 'Monitorar a necessidade de treinamentos e atualizações.', 'Concluído', '2026-05-31', NULL),
  ('Jurema', 'PE', 2026, 5, 'Informar ao cliente sobre as principais implementações do módulo.', 'Concluído', '2026-05-31', NULL),
  ('Jurema', 'PE', 2026, 5, 'Acompanhar e gerenciar as demandas de programação e/ou técnicas.', 'Concluído', '2026-05-31', NULL),
  ('Jurema', 'PE', 2026, 5, 'No portal da transparência, acompanhar mensalmente as pendências, encaminhá-las ao responsável e enviar o Integra por e-mail.', 'Concluído', '2026-05-31', NULL),
  ('Jurema', 'PE', 2026, 6, 'Monitorar a alimentação do sistema pelo cliente, verificando possível ausência ou má alimentação.', 'Concluído', '2026-06-30', NULL),
  ('Jurema', 'PE', 2026, 6, 'Verificar se os clientes utilizam os principais recursos e benefícios do sistema do módulo atuante.', 'Concluído', '2026-06-30', NULL),
  ('Jurema', 'PE', 2026, 6, 'Acompanhar as integrações, quando aplicável.', 'Concluído', '2026-06-30', NULL),
  ('Jurema', 'PE', 2026, 6, 'Monitorar a necessidade de treinamentos e atualizações.', 'Concluído', '2026-06-30', NULL),
  ('Jurema', 'PE', 2026, 6, 'Informar ao cliente sobre as principais implementações do módulo.', 'Concluído', '2026-06-30', NULL),
  ('Jurema', 'PE', 2026, 6, 'Acompanhar e gerenciar as demandas de programação e/ou técnicas.', 'Concluído', '2026-06-30', NULL),
  ('Jurema', 'PE', 2026, 6, 'No portal da transparência, acompanhar mensalmente as pendências, encaminhá-las ao responsável e enviar o Integra por e-mail.', 'Pendente', '1899-12-30', NULL),
  ('Jurema', 'PE', 2026, 7, 'Monitorar a alimentação do sistema pelo cliente, verificando possível ausência ou má alimentação.', 'Concluído', '2026-07-31', NULL),
  ('Jurema', 'PE', 2026, 7, 'Verificar se os clientes utilizam os principais recursos e benefícios do sistema do módulo atuante.', 'Concluído', '2026-07-31', NULL),
  ('Jurema', 'PE', 2026, 7, 'Acompanhar as integrações, quando aplicável.', 'Concluído', '2026-07-31', NULL),
  ('Jurema', 'PE', 2026, 7, 'Monitorar a necessidade de treinamentos e atualizações.', 'Concluído', '2026-07-31', NULL),
  ('Jurema', 'PE', 2026, 7, 'Informar ao cliente sobre as principais implementações do módulo.', 'Concluído', '2026-07-31', NULL),
  ('Jurema', 'PE', 2026, 7, 'Acompanhar e gerenciar as demandas de programação e/ou técnicas.', 'Concluído', '2026-07-31', NULL),
  ('Jurema', 'PE', 2026, 7, 'No portal da transparência, acompanhar mensalmente as pendências, encaminhá-las ao responsável e enviar o Integra por e-mail.', 'Concluído', '2026-07-31', NULL),
  ('Jurema', 'PE', 2026, 8, 'Monitorar a alimentação do sistema pelo cliente, verificando possível ausência ou má alimentação.', 'Pendente', '1899-12-30', NULL),
  ('Jurema', 'PE', 2026, 8, 'Verificar se os clientes utilizam os principais recursos e benefícios do sistema do módulo atuante.', 'Pendente', '1899-12-30', NULL),
  ('Jurema', 'PE', 2026, 8, 'Acompanhar as integrações, quando aplicável.', 'Pendente', '1899-12-30', NULL),
  ('Jurema', 'PE', 2026, 8, 'Monitorar a necessidade de treinamentos e atualizações.', 'Pendente', '1899-12-30', NULL),
  ('Jurema', 'PE', 2026, 8, 'Informar ao cliente sobre as principais implementações do módulo.', 'Pendente', '1899-12-30', NULL),
  ('Jurema', 'PE', 2026, 8, 'Acompanhar e gerenciar as demandas de programação e/ou técnicas.', 'Pendente', '1899-12-30', NULL),
  ('Jurema', 'PE', 2026, 8, 'No portal da transparência, acompanhar mensalmente as pendências, encaminhá-las ao responsável e enviar o Integra por e-mail.', 'Pendente', '1899-12-30', NULL),
  ('Jurema', 'PE', 2026, 9, 'Monitorar a alimentação do sistema pelo cliente, verificando possível ausência ou má alimentação.', 'Pendente', '1899-12-30', NULL),
  ('Jurema', 'PE', 2026, 9, 'Verificar se os clientes utilizam os principais recursos e benefícios do sistema do módulo atuante.', 'Pendente', '1899-12-30', NULL),
  ('Jurema', 'PE', 2026, 9, 'Acompanhar as integrações, quando aplicável.', 'Pendente', '1899-12-30', NULL),
  ('Jurema', 'PE', 2026, 9, 'Monitorar a necessidade de treinamentos e atualizações.', 'Pendente', '1899-12-30', NULL),
  ('Jurema', 'PE', 2026, 9, 'Informar ao cliente sobre as principais implementações do módulo.', 'Pendente', '1899-12-30', NULL),
  ('Jurema', 'PE', 2026, 9, 'Acompanhar e gerenciar as demandas de programação e/ou técnicas.', 'Pendente', '1899-12-30', NULL),
  ('Jurema', 'PE', 2026, 9, 'No portal da transparência, acompanhar mensalmente as pendências, encaminhá-las ao responsável e enviar o Integra por e-mail.', 'Pendente', '1899-12-30', NULL),
  ('Jurema', 'PE', 2026, 10, 'Monitorar a alimentação do sistema pelo cliente, verificando possível ausência ou má alimentação.', 'Pendente', '1899-12-30', NULL),
  ('Jurema', 'PE', 2026, 10, 'Verificar se os clientes utilizam os principais recursos e benefícios do sistema do módulo atuante.', 'Pendente', '1899-12-30', NULL),
  ('Jurema', 'PE', 2026, 10, 'Acompanhar as integrações, quando aplicável.', 'Pendente', '1899-12-30', NULL),
  ('Jurema', 'PE', 2026, 10, 'Monitorar a necessidade de treinamentos e atualizações.', 'Pendente', '1899-12-30', NULL),
  ('Jurema', 'PE', 2026, 10, 'Informar ao cliente sobre as principais implementações do módulo.', 'Pendente', '1899-12-30', NULL),
  ('Jurema', 'PE', 2026, 10, 'Acompanhar e gerenciar as demandas de programação e/ou técnicas.', 'Pendente', '1899-12-30', NULL),
  ('Jurema', 'PE', 2026, 10, 'No portal da transparência, acompanhar mensalmente as pendências, encaminhá-las ao responsável e enviar o Integra por e-mail.', 'Pendente', '1899-12-30', NULL),
  ('Jurema', 'PE', 2026, 11, 'Monitorar a alimentação do sistema pelo cliente, verificando possível ausência ou má alimentação.', 'Pendente', '1899-12-30', NULL),
  ('Jurema', 'PE', 2026, 11, 'Verificar se os clientes utilizam os principais recursos e benefícios do sistema do módulo atuante.', 'Pendente', '1899-12-30', NULL),
  ('Jurema', 'PE', 2026, 11, 'Acompanhar as integrações, quando aplicável.', 'Pendente', '1899-12-30', NULL),
  ('Jurema', 'PE', 2026, 11, 'Monitorar a necessidade de treinamentos e atualizações.', 'Pendente', '1899-12-30', NULL),
  ('Jurema', 'PE', 2026, 11, 'Informar ao cliente sobre as principais implementações do módulo.', 'Pendente', '1899-12-30', NULL),
  ('Jurema', 'PE', 2026, 11, 'Acompanhar e gerenciar as demandas de programação e/ou técnicas.', 'Pendente', '1899-12-30', NULL),
  ('Jurema', 'PE', 2026, 11, 'No portal da transparência, acompanhar mensalmente as pendências, encaminhá-las ao responsável e enviar o Integra por e-mail.', 'Pendente', '1899-12-30', NULL),
  ('Jurema', 'PE', 2026, 12, 'Monitorar a alimentação do sistema pelo cliente, verificando possível ausência ou má alimentação.', 'Pendente', '1899-12-30', NULL),
  ('Jurema', 'PE', 2026, 12, 'Verificar se os clientes utilizam os principais recursos e benefícios do sistema do módulo atuante.', 'Pendente', '1899-12-30', NULL),
  ('Jurema', 'PE', 2026, 12, 'Acompanhar as integrações, quando aplicável.', 'Pendente', '1899-12-30', NULL),
  ('Jurema', 'PE', 2026, 12, 'Monitorar a necessidade de treinamentos e atualizações.', 'Pendente', '1899-12-30', NULL),
  ('Jurema', 'PE', 2026, 12, 'Informar ao cliente sobre as principais implementações do módulo.', 'Pendente', '1899-12-30', NULL),
  ('Jurema', 'PE', 2026, 12, 'Acompanhar e gerenciar as demandas de programação e/ou técnicas.', 'Pendente', '1899-12-30', NULL),
  ('Jurema', 'PE', 2026, 12, 'No portal da transparência, acompanhar mensalmente as pendências, encaminhá-las ao responsável e enviar o Integra por e-mail.', 'Pendente', '1899-12-30', NULL),
  ('Lajedo', 'PE', 2026, 1, 'Monitorar a alimentação do sistema pelo cliente, verificando possível ausência ou má alimentação.', 'Concluído', '2026-01-31', NULL),
  ('Lajedo', 'PE', 2026, 1, 'Verificar se os clientes utilizam os principais recursos e benefícios do sistema do módulo atuante.', 'Concluído', '2026-01-31', NULL),
  ('Lajedo', 'PE', 2026, 1, 'Acompanhar as integrações, quando aplicável.', 'Concluído', '2026-01-31', NULL),
  ('Lajedo', 'PE', 2026, 1, 'Monitorar a necessidade de treinamentos e atualizações.', 'Concluído', '2026-01-31', NULL),
  ('Lajedo', 'PE', 2026, 1, 'Informar ao cliente sobre as principais implementações do módulo.', 'Concluído', '2026-01-31', NULL),
  ('Lajedo', 'PE', 2026, 1, 'Acompanhar e gerenciar as demandas de programação e/ou técnicas.', 'Concluído', '2026-01-31', NULL),
  ('Lajedo', 'PE', 2026, 1, 'No portal da transparência, acompanhar mensalmente as pendências, encaminhá-las ao responsável e enviar o Integra por e-mail.', 'Concluído', '2026-01-31', NULL),
  ('Lajedo', 'PE', 2026, 2, 'Monitorar a alimentação do sistema pelo cliente, verificando possível ausência ou má alimentação.', 'Concluído', '2026-02-28', NULL),
  ('Lajedo', 'PE', 2026, 2, 'Verificar se os clientes utilizam os principais recursos e benefícios do sistema do módulo atuante.', 'Concluído', '2026-02-28', NULL),
  ('Lajedo', 'PE', 2026, 2, 'Acompanhar as integrações, quando aplicável.', 'Concluído', '2026-02-28', NULL),
  ('Lajedo', 'PE', 2026, 2, 'Monitorar a necessidade de treinamentos e atualizações.', 'Concluído', '2026-02-28', NULL),
  ('Lajedo', 'PE', 2026, 2, 'Informar ao cliente sobre as principais implementações do módulo.', 'Concluído', '2026-02-28', NULL),
  ('Lajedo', 'PE', 2026, 2, 'Acompanhar e gerenciar as demandas de programação e/ou técnicas.', 'Concluído', '2026-02-28', NULL),
  ('Lajedo', 'PE', 2026, 2, 'No portal da transparência, acompanhar mensalmente as pendências, encaminhá-las ao responsável e enviar o Integra por e-mail.', 'Concluído', '2026-02-28', NULL),
  ('Lajedo', 'PE', 2026, 3, 'Monitorar a alimentação do sistema pelo cliente, verificando possível ausência ou má alimentação.', 'Concluído', '2026-03-31', NULL),
  ('Lajedo', 'PE', 2026, 3, 'Verificar se os clientes utilizam os principais recursos e benefícios do sistema do módulo atuante.', 'Concluído', '2026-03-31', NULL),
  ('Lajedo', 'PE', 2026, 3, 'Acompanhar as integrações, quando aplicável.', 'Concluído', '2026-03-31', NULL),
  ('Lajedo', 'PE', 2026, 3, 'Monitorar a necessidade de treinamentos e atualizações.', 'Concluído', '2026-03-31', NULL),
  ('Lajedo', 'PE', 2026, 3, 'Informar ao cliente sobre as principais implementações do módulo.', 'Concluído', '2026-03-31', NULL),
  ('Lajedo', 'PE', 2026, 3, 'Acompanhar e gerenciar as demandas de programação e/ou técnicas.', 'Concluído', '2026-03-31', NULL),
  ('Lajedo', 'PE', 2026, 3, 'No portal da transparência, acompanhar mensalmente as pendências, encaminhá-las ao responsável e enviar o Integra por e-mail.', 'Concluído', '2026-03-31', NULL),
  ('Lajedo', 'PE', 2026, 4, 'Monitorar a alimentação do sistema pelo cliente, verificando possível ausência ou má alimentação.', 'Concluído', '2026-04-30', NULL),
  ('Lajedo', 'PE', 2026, 4, 'Verificar se os clientes utilizam os principais recursos e benefícios do sistema do módulo atuante.', 'Concluído', '2026-04-30', NULL),
  ('Lajedo', 'PE', 2026, 4, 'Acompanhar as integrações, quando aplicável.', 'Concluído', '2026-04-30', NULL),
  ('Lajedo', 'PE', 2026, 4, 'Monitorar a necessidade de treinamentos e atualizações.', 'Concluído', '2026-04-30', NULL),
  ('Lajedo', 'PE', 2026, 4, 'Informar ao cliente sobre as principais implementações do módulo.', 'Concluído', '2026-04-30', NULL),
  ('Lajedo', 'PE', 2026, 4, 'Acompanhar e gerenciar as demandas de programação e/ou técnicas.', 'Concluído', '2026-04-30', NULL),
  ('Lajedo', 'PE', 2026, 4, 'No portal da transparência, acompanhar mensalmente as pendências, encaminhá-las ao responsável e enviar o Integra por e-mail.', 'Concluído', '2026-04-30', NULL),
  ('Lajedo', 'PE', 2026, 5, 'Monitorar a alimentação do sistema pelo cliente, verificando possível ausência ou má alimentação.', 'Concluído', '2026-05-31', NULL),
  ('Lajedo', 'PE', 2026, 5, 'Verificar se os clientes utilizam os principais recursos e benefícios do sistema do módulo atuante.', 'Concluído', '2026-05-31', NULL),
  ('Lajedo', 'PE', 2026, 5, 'Acompanhar as integrações, quando aplicável.', 'Concluído', '2026-05-31', NULL),
  ('Lajedo', 'PE', 2026, 5, 'Monitorar a necessidade de treinamentos e atualizações.', 'Concluído', '2026-05-31', NULL),
  ('Lajedo', 'PE', 2026, 5, 'Informar ao cliente sobre as principais implementações do módulo.', 'Concluído', '2026-05-31', NULL),
  ('Lajedo', 'PE', 2026, 5, 'Acompanhar e gerenciar as demandas de programação e/ou técnicas.', 'Concluído', '2026-05-31', NULL),
  ('Lajedo', 'PE', 2026, 5, 'No portal da transparência, acompanhar mensalmente as pendências, encaminhá-las ao responsável e enviar o Integra por e-mail.', 'Concluído', '2026-05-31', NULL),
  ('Lajedo', 'PE', 2026, 6, 'Monitorar a alimentação do sistema pelo cliente, verificando possível ausência ou má alimentação.', 'Concluído', '2026-06-30', NULL),
  ('Lajedo', 'PE', 2026, 6, 'Verificar se os clientes utilizam os principais recursos e benefícios do sistema do módulo atuante.', 'Concluído', '2026-06-30', NULL),
  ('Lajedo', 'PE', 2026, 6, 'Acompanhar as integrações, quando aplicável.', 'Concluído', '2026-06-30', NULL),
  ('Lajedo', 'PE', 2026, 6, 'Monitorar a necessidade de treinamentos e atualizações.', 'Concluído', '2026-06-30', NULL),
  ('Lajedo', 'PE', 2026, 6, 'Informar ao cliente sobre as principais implementações do módulo.', 'Concluído', '2026-06-30', NULL),
  ('Lajedo', 'PE', 2026, 6, 'Acompanhar e gerenciar as demandas de programação e/ou técnicas.', 'Concluído', '2026-06-30', NULL),
  ('Lajedo', 'PE', 2026, 6, 'No portal da transparência, acompanhar mensalmente as pendências, encaminhá-las ao responsável e enviar o Integra por e-mail.', 'Concluído', '2026-07-31', NULL),
  ('Lajedo', 'PE', 2026, 7, 'Monitorar a alimentação do sistema pelo cliente, verificando possível ausência ou má alimentação.', 'Concluído', '2026-07-31', NULL),
  ('Lajedo', 'PE', 2026, 7, 'Verificar se os clientes utilizam os principais recursos e benefícios do sistema do módulo atuante.', 'Concluído', '2026-07-31', NULL),
  ('Lajedo', 'PE', 2026, 7, 'Acompanhar as integrações, quando aplicável.', 'Concluído', '2026-07-31', NULL),
  ('Lajedo', 'PE', 2026, 7, 'Monitorar a necessidade de treinamentos e atualizações.', 'Concluído', '2026-07-31', NULL),
  ('Lajedo', 'PE', 2026, 7, 'Informar ao cliente sobre as principais implementações do módulo.', 'Concluído', '2026-07-31', NULL),
  ('Lajedo', 'PE', 2026, 7, 'Acompanhar e gerenciar as demandas de programação e/ou técnicas.', 'Concluído', '2026-07-31', NULL),
  ('Lajedo', 'PE', 2026, 7, 'No portal da transparência, acompanhar mensalmente as pendências, encaminhá-las ao responsável e enviar o Integra por e-mail.', 'Concluído', '2026-07-31', NULL),
  ('Lajedo', 'PE', 2026, 8, 'Monitorar a alimentação do sistema pelo cliente, verificando possível ausência ou má alimentação.', 'Pendente', '1899-12-30', NULL),
  ('Lajedo', 'PE', 2026, 8, 'Verificar se os clientes utilizam os principais recursos e benefícios do sistema do módulo atuante.', 'Pendente', '1899-12-30', NULL),
  ('Lajedo', 'PE', 2026, 8, 'Acompanhar as integrações, quando aplicável.', 'Pendente', '1899-12-30', NULL),
  ('Lajedo', 'PE', 2026, 8, 'Monitorar a necessidade de treinamentos e atualizações.', 'Pendente', '1899-12-30', NULL),
  ('Lajedo', 'PE', 2026, 8, 'Informar ao cliente sobre as principais implementações do módulo.', 'Pendente', '1899-12-30', NULL),
  ('Lajedo', 'PE', 2026, 8, 'Acompanhar e gerenciar as demandas de programação e/ou técnicas.', 'Pendente', '1899-12-30', NULL),
  ('Lajedo', 'PE', 2026, 8, 'No portal da transparência, acompanhar mensalmente as pendências, encaminhá-las ao responsável e enviar o Integra por e-mail.', 'Pendente', '1899-12-30', NULL),
  ('Lajedo', 'PE', 2026, 9, 'Monitorar a alimentação do sistema pelo cliente, verificando possível ausência ou má alimentação.', 'Pendente', '1899-12-30', NULL),
  ('Lajedo', 'PE', 2026, 9, 'Verificar se os clientes utilizam os principais recursos e benefícios do sistema do módulo atuante.', 'Pendente', '1899-12-30', NULL),
  ('Lajedo', 'PE', 2026, 9, 'Acompanhar as integrações, quando aplicável.', 'Pendente', '1899-12-30', NULL),
  ('Lajedo', 'PE', 2026, 9, 'Monitorar a necessidade de treinamentos e atualizações.', 'Pendente', '1899-12-30', NULL),
  ('Lajedo', 'PE', 2026, 9, 'Informar ao cliente sobre as principais implementações do módulo.', 'Pendente', '1899-12-30', NULL),
  ('Lajedo', 'PE', 2026, 9, 'Acompanhar e gerenciar as demandas de programação e/ou técnicas.', 'Pendente', '1899-12-30', NULL),
  ('Lajedo', 'PE', 2026, 9, 'No portal da transparência, acompanhar mensalmente as pendências, encaminhá-las ao responsável e enviar o Integra por e-mail.', 'Pendente', '1899-12-30', NULL),
  ('Lajedo', 'PE', 2026, 10, 'Monitorar a alimentação do sistema pelo cliente, verificando possível ausência ou má alimentação.', 'Pendente', '1899-12-30', NULL),
  ('Lajedo', 'PE', 2026, 10, 'Verificar se os clientes utilizam os principais recursos e benefícios do sistema do módulo atuante.', 'Pendente', '1899-12-30', NULL),
  ('Lajedo', 'PE', 2026, 10, 'Acompanhar as integrações, quando aplicável.', 'Pendente', '1899-12-30', NULL),
  ('Lajedo', 'PE', 2026, 10, 'Monitorar a necessidade de treinamentos e atualizações.', 'Pendente', '1899-12-30', NULL),
  ('Lajedo', 'PE', 2026, 10, 'Informar ao cliente sobre as principais implementações do módulo.', 'Pendente', '1899-12-30', NULL),
  ('Lajedo', 'PE', 2026, 10, 'Acompanhar e gerenciar as demandas de programação e/ou técnicas.', 'Pendente', '1899-12-30', NULL),
  ('Lajedo', 'PE', 2026, 10, 'No portal da transparência, acompanhar mensalmente as pendências, encaminhá-las ao responsável e enviar o Integra por e-mail.', 'Pendente', '1899-12-30', NULL),
  ('Lajedo', 'PE', 2026, 11, 'Monitorar a alimentação do sistema pelo cliente, verificando possível ausência ou má alimentação.', 'Pendente', '1899-12-30', NULL),
  ('Lajedo', 'PE', 2026, 11, 'Verificar se os clientes utilizam os principais recursos e benefícios do sistema do módulo atuante.', 'Pendente', '1899-12-30', NULL),
  ('Lajedo', 'PE', 2026, 11, 'Acompanhar as integrações, quando aplicável.', 'Pendente', '1899-12-30', NULL),
  ('Lajedo', 'PE', 2026, 11, 'Monitorar a necessidade de treinamentos e atualizações.', 'Pendente', '1899-12-30', NULL),
  ('Lajedo', 'PE', 2026, 11, 'Informar ao cliente sobre as principais implementações do módulo.', 'Pendente', '1899-12-30', NULL),
  ('Lajedo', 'PE', 2026, 11, 'Acompanhar e gerenciar as demandas de programação e/ou técnicas.', 'Pendente', '1899-12-30', NULL),
  ('Lajedo', 'PE', 2026, 11, 'No portal da transparência, acompanhar mensalmente as pendências, encaminhá-las ao responsável e enviar o Integra por e-mail.', 'Pendente', '1899-12-30', NULL),
  ('Lajedo', 'PE', 2026, 12, 'Monitorar a alimentação do sistema pelo cliente, verificando possível ausência ou má alimentação.', 'Pendente', '1899-12-30', NULL),
  ('Lajedo', 'PE', 2026, 12, 'Verificar se os clientes utilizam os principais recursos e benefícios do sistema do módulo atuante.', 'Pendente', '1899-12-30', NULL),
  ('Lajedo', 'PE', 2026, 12, 'Acompanhar as integrações, quando aplicável.', 'Pendente', '1899-12-30', NULL),
  ('Lajedo', 'PE', 2026, 12, 'Monitorar a necessidade de treinamentos e atualizações.', 'Pendente', '1899-12-30', NULL),
  ('Lajedo', 'PE', 2026, 12, 'Informar ao cliente sobre as principais implementações do módulo.', 'Pendente', '1899-12-30', NULL),
  ('Lajedo', 'PE', 2026, 12, 'Acompanhar e gerenciar as demandas de programação e/ou técnicas.', 'Pendente', '1899-12-30', NULL),
  ('Lajedo', 'PE', 2026, 12, 'No portal da transparência, acompanhar mensalmente as pendências, encaminhá-las ao responsável e enviar o Integra por e-mail.', 'Pendente', '1899-12-30', NULL),
  ('Solidão', 'PE', 2026, 1, 'Monitorar a alimentação do sistema pelo cliente, verificando possível ausência ou má alimentação.', 'Concluído', '2026-01-31', NULL),
  ('Solidão', 'PE', 2026, 1, 'Verificar se os clientes utilizam os principais recursos e benefícios do sistema do módulo atuante.', 'Concluído', '2026-01-31', NULL),
  ('Solidão', 'PE', 2026, 1, 'Acompanhar as integrações, quando aplicável.', 'Concluído', '2026-01-31', NULL),
  ('Solidão', 'PE', 2026, 1, 'Monitorar a necessidade de treinamentos e atualizações.', 'Concluído', '2026-01-31', NULL),
  ('Solidão', 'PE', 2026, 1, 'Informar ao cliente sobre as principais implementações do módulo.', 'Concluído', '2026-01-31', NULL),
  ('Solidão', 'PE', 2026, 1, 'Acompanhar e gerenciar as demandas de programação e/ou técnicas.', 'Concluído', '2026-01-31', NULL),
  ('Solidão', 'PE', 2026, 1, 'No portal da transparência, acompanhar mensalmente as pendências, encaminhá-las ao responsável e enviar o Integra por e-mail.', 'Concluído', '2026-01-31', NULL),
  ('Solidão', 'PE', 2026, 2, 'Monitorar a alimentação do sistema pelo cliente, verificando possível ausência ou má alimentação.', 'Concluído', '2026-02-28', NULL),
  ('Solidão', 'PE', 2026, 2, 'Verificar se os clientes utilizam os principais recursos e benefícios do sistema do módulo atuante.', 'Concluído', '2026-02-28', NULL),
  ('Solidão', 'PE', 2026, 2, 'Acompanhar as integrações, quando aplicável.', 'Concluído', '2026-02-28', NULL),
  ('Solidão', 'PE', 2026, 2, 'Monitorar a necessidade de treinamentos e atualizações.', 'Concluído', '2026-02-28', NULL),
  ('Solidão', 'PE', 2026, 2, 'Informar ao cliente sobre as principais implementações do módulo.', 'Concluído', '2026-02-28', NULL),
  ('Solidão', 'PE', 2026, 2, 'Acompanhar e gerenciar as demandas de programação e/ou técnicas.', 'Concluído', '2026-02-28', NULL),
  ('Solidão', 'PE', 2026, 2, 'No portal da transparência, acompanhar mensalmente as pendências, encaminhá-las ao responsável e enviar o Integra por e-mail.', 'Concluído', '2026-02-28', NULL),
  ('Solidão', 'PE', 2026, 3, 'Monitorar a alimentação do sistema pelo cliente, verificando possível ausência ou má alimentação.', 'Concluído', '2026-03-31', NULL),
  ('Solidão', 'PE', 2026, 3, 'Verificar se os clientes utilizam os principais recursos e benefícios do sistema do módulo atuante.', 'Concluído', '2026-03-31', NULL),
  ('Solidão', 'PE', 2026, 3, 'Acompanhar as integrações, quando aplicável.', 'Concluído', '2026-03-31', NULL),
  ('Solidão', 'PE', 2026, 3, 'Monitorar a necessidade de treinamentos e atualizações.', 'Concluído', '2026-03-31', NULL),
  ('Solidão', 'PE', 2026, 3, 'Informar ao cliente sobre as principais implementações do módulo.', 'Concluído', '2026-03-31', NULL),
  ('Solidão', 'PE', 2026, 3, 'Acompanhar e gerenciar as demandas de programação e/ou técnicas.', 'Concluído', '2026-03-31', NULL),
  ('Solidão', 'PE', 2026, 3, 'No portal da transparência, acompanhar mensalmente as pendências, encaminhá-las ao responsável e enviar o Integra por e-mail.', 'Concluído', '2026-03-31', NULL),
  ('Solidão', 'PE', 2026, 4, 'Monitorar a alimentação do sistema pelo cliente, verificando possível ausência ou má alimentação.', 'Concluído', '2026-04-30', NULL),
  ('Solidão', 'PE', 2026, 4, 'Verificar se os clientes utilizam os principais recursos e benefícios do sistema do módulo atuante.', 'Concluído', '2026-04-30', NULL),
  ('Solidão', 'PE', 2026, 4, 'Acompanhar as integrações, quando aplicável.', 'Concluído', '2026-04-30', NULL),
  ('Solidão', 'PE', 2026, 4, 'Monitorar a necessidade de treinamentos e atualizações.', 'Concluído', '2026-04-30', NULL),
  ('Solidão', 'PE', 2026, 4, 'Informar ao cliente sobre as principais implementações do módulo.', 'Concluído', '2026-04-30', NULL),
  ('Solidão', 'PE', 2026, 4, 'Acompanhar e gerenciar as demandas de programação e/ou técnicas.', 'Concluído', '2026-04-30', NULL),
  ('Solidão', 'PE', 2026, 4, 'No portal da transparência, acompanhar mensalmente as pendências, encaminhá-las ao responsável e enviar o Integra por e-mail.', 'Concluído', '2026-04-30', NULL),
  ('Solidão', 'PE', 2026, 5, 'Monitorar a alimentação do sistema pelo cliente, verificando possível ausência ou má alimentação.', 'Concluído', '2026-05-31', NULL),
  ('Solidão', 'PE', 2026, 5, 'Verificar se os clientes utilizam os principais recursos e benefícios do sistema do módulo atuante.', 'Concluído', '2026-05-31', NULL),
  ('Solidão', 'PE', 2026, 5, 'Acompanhar as integrações, quando aplicável.', 'Concluído', '2026-05-31', NULL),
  ('Solidão', 'PE', 2026, 5, 'Monitorar a necessidade de treinamentos e atualizações.', 'Concluído', '2026-05-31', NULL),
  ('Solidão', 'PE', 2026, 5, 'Informar ao cliente sobre as principais implementações do módulo.', 'Concluído', '2026-05-31', NULL),
  ('Solidão', 'PE', 2026, 5, 'Acompanhar e gerenciar as demandas de programação e/ou técnicas.', 'Concluído', '2026-05-31', NULL),
  ('Solidão', 'PE', 2026, 5, 'No portal da transparência, acompanhar mensalmente as pendências, encaminhá-las ao responsável e enviar o Integra por e-mail.', 'Concluído', '2026-05-31', NULL),
  ('Solidão', 'PE', 2026, 6, 'Monitorar a alimentação do sistema pelo cliente, verificando possível ausência ou má alimentação.', 'Concluído', '2026-06-30', NULL),
  ('Solidão', 'PE', 2026, 6, 'Verificar se os clientes utilizam os principais recursos e benefícios do sistema do módulo atuante.', 'Concluído', '2026-06-30', NULL),
  ('Solidão', 'PE', 2026, 6, 'Acompanhar as integrações, quando aplicável.', 'Concluído', '2026-06-30', NULL),
  ('Solidão', 'PE', 2026, 6, 'Monitorar a necessidade de treinamentos e atualizações.', 'Concluído', '2026-06-30', NULL),
  ('Solidão', 'PE', 2026, 6, 'Informar ao cliente sobre as principais implementações do módulo.', 'Concluído', '2026-06-30', NULL),
  ('Solidão', 'PE', 2026, 6, 'Acompanhar e gerenciar as demandas de programação e/ou técnicas.', 'Concluído', '2026-06-30', NULL),
  ('Solidão', 'PE', 2026, 6, 'No portal da transparência, acompanhar mensalmente as pendências, encaminhá-las ao responsável e enviar o Integra por e-mail.', 'Concluído', '2026-07-31', NULL),
  ('Solidão', 'PE', 2026, 7, 'Monitorar a alimentação do sistema pelo cliente, verificando possível ausência ou má alimentação.', 'Concluído', '2026-07-31', NULL),
  ('Solidão', 'PE', 2026, 7, 'Verificar se os clientes utilizam os principais recursos e benefícios do sistema do módulo atuante.', 'Concluído', '2026-07-31', NULL),
  ('Solidão', 'PE', 2026, 7, 'Acompanhar as integrações, quando aplicável.', 'Concluído', '2026-07-31', NULL),
  ('Solidão', 'PE', 2026, 7, 'Monitorar a necessidade de treinamentos e atualizações.', 'Concluído', '2026-07-31', NULL),
  ('Solidão', 'PE', 2026, 7, 'Informar ao cliente sobre as principais implementações do módulo.', 'Concluído', '2026-07-31', NULL),
  ('Solidão', 'PE', 2026, 7, 'Acompanhar e gerenciar as demandas de programação e/ou técnicas.', 'Concluído', '2026-07-31', NULL),
  ('Solidão', 'PE', 2026, 7, 'No portal da transparência, acompanhar mensalmente as pendências, encaminhá-las ao responsável e enviar o Integra por e-mail.', 'Concluído', '2026-07-31', NULL),
  ('Solidão', 'PE', 2026, 8, 'Monitorar a alimentação do sistema pelo cliente, verificando possível ausência ou má alimentação.', 'Pendente', '1899-12-30', NULL),
  ('Solidão', 'PE', 2026, 8, 'Verificar se os clientes utilizam os principais recursos e benefícios do sistema do módulo atuante.', 'Pendente', '1899-12-30', NULL),
  ('Solidão', 'PE', 2026, 8, 'Acompanhar as integrações, quando aplicável.', 'Pendente', '1899-12-30', NULL),
  ('Solidão', 'PE', 2026, 8, 'Monitorar a necessidade de treinamentos e atualizações.', 'Pendente', '1899-12-30', NULL),
  ('Solidão', 'PE', 2026, 8, 'Informar ao cliente sobre as principais implementações do módulo.', 'Pendente', '1899-12-30', NULL),
  ('Solidão', 'PE', 2026, 8, 'Acompanhar e gerenciar as demandas de programação e/ou técnicas.', 'Pendente', '1899-12-30', NULL),
  ('Solidão', 'PE', 2026, 8, 'No portal da transparência, acompanhar mensalmente as pendências, encaminhá-las ao responsável e enviar o Integra por e-mail.', 'Pendente', '1899-12-30', NULL),
  ('Solidão', 'PE', 2026, 9, 'Monitorar a alimentação do sistema pelo cliente, verificando possível ausência ou má alimentação.', 'Pendente', '1899-12-30', NULL),
  ('Solidão', 'PE', 2026, 9, 'Verificar se os clientes utilizam os principais recursos e benefícios do sistema do módulo atuante.', 'Pendente', '1899-12-30', NULL),
  ('Solidão', 'PE', 2026, 9, 'Acompanhar as integrações, quando aplicável.', 'Pendente', '1899-12-30', NULL),
  ('Solidão', 'PE', 2026, 9, 'Monitorar a necessidade de treinamentos e atualizações.', 'Pendente', '1899-12-30', NULL),
  ('Solidão', 'PE', 2026, 9, 'Informar ao cliente sobre as principais implementações do módulo.', 'Pendente', '1899-12-30', NULL),
  ('Solidão', 'PE', 2026, 9, 'Acompanhar e gerenciar as demandas de programação e/ou técnicas.', 'Pendente', '1899-12-30', NULL),
  ('Solidão', 'PE', 2026, 9, 'No portal da transparência, acompanhar mensalmente as pendências, encaminhá-las ao responsável e enviar o Integra por e-mail.', 'Pendente', '1899-12-30', NULL),
  ('Solidão', 'PE', 2026, 10, 'Monitorar a alimentação do sistema pelo cliente, verificando possível ausência ou má alimentação.', 'Pendente', '1899-12-30', NULL),
  ('Solidão', 'PE', 2026, 10, 'Verificar se os clientes utilizam os principais recursos e benefícios do sistema do módulo atuante.', 'Pendente', '1899-12-30', NULL),
  ('Solidão', 'PE', 2026, 10, 'Acompanhar as integrações, quando aplicável.', 'Pendente', '1899-12-30', NULL),
  ('Solidão', 'PE', 2026, 10, 'Monitorar a necessidade de treinamentos e atualizações.', 'Pendente', '1899-12-30', NULL),
  ('Solidão', 'PE', 2026, 10, 'Informar ao cliente sobre as principais implementações do módulo.', 'Pendente', '1899-12-30', NULL),
  ('Solidão', 'PE', 2026, 10, 'Acompanhar e gerenciar as demandas de programação e/ou técnicas.', 'Pendente', '1899-12-30', NULL),
  ('Solidão', 'PE', 2026, 10, 'No portal da transparência, acompanhar mensalmente as pendências, encaminhá-las ao responsável e enviar o Integra por e-mail.', 'Pendente', '1899-12-30', NULL),
  ('Solidão', 'PE', 2026, 11, 'Monitorar a alimentação do sistema pelo cliente, verificando possível ausência ou má alimentação.', 'Pendente', '1899-12-30', NULL),
  ('Solidão', 'PE', 2026, 11, 'Verificar se os clientes utilizam os principais recursos e benefícios do sistema do módulo atuante.', 'Pendente', '1899-12-30', NULL),
  ('Solidão', 'PE', 2026, 11, 'Acompanhar as integrações, quando aplicável.', 'Pendente', '1899-12-30', NULL),
  ('Solidão', 'PE', 2026, 11, 'Monitorar a necessidade de treinamentos e atualizações.', 'Pendente', '1899-12-30', NULL),
  ('Solidão', 'PE', 2026, 11, 'Informar ao cliente sobre as principais implementações do módulo.', 'Pendente', '1899-12-30', NULL),
  ('Solidão', 'PE', 2026, 11, 'Acompanhar e gerenciar as demandas de programação e/ou técnicas.', 'Pendente', '1899-12-30', NULL),
  ('Solidão', 'PE', 2026, 11, 'No portal da transparência, acompanhar mensalmente as pendências, encaminhá-las ao responsável e enviar o Integra por e-mail.', 'Pendente', '1899-12-30', NULL),
  ('Solidão', 'PE', 2026, 12, 'Monitorar a alimentação do sistema pelo cliente, verificando possível ausência ou má alimentação.', 'Pendente', '1899-12-30', NULL),
  ('Solidão', 'PE', 2026, 12, 'Verificar se os clientes utilizam os principais recursos e benefícios do sistema do módulo atuante.', 'Pendente', '1899-12-30', NULL),
  ('Solidão', 'PE', 2026, 12, 'Acompanhar as integrações, quando aplicável.', 'Pendente', '1899-12-30', NULL),
  ('Solidão', 'PE', 2026, 12, 'Monitorar a necessidade de treinamentos e atualizações.', 'Pendente', '1899-12-30', NULL),
  ('Solidão', 'PE', 2026, 12, 'Informar ao cliente sobre as principais implementações do módulo.', 'Pendente', '1899-12-30', NULL),
  ('Solidão', 'PE', 2026, 12, 'Acompanhar e gerenciar as demandas de programação e/ou técnicas.', 'Pendente', '1899-12-30', NULL),
  ('Solidão', 'PE', 2026, 12, 'No portal da transparência, acompanhar mensalmente as pendências, encaminhá-las ao responsável e enviar o Integra por e-mail.', 'Pendente', '1899-12-30', NULL),
  ('São José da Coroa Grande', 'PE', 2026, 1, 'Monitorar a alimentação do sistema pelo cliente, verificando possível ausência ou má alimentação.', 'Concluído', '2026-01-31', NULL),
  ('São José da Coroa Grande', 'PE', 2026, 1, 'Verificar se os clientes utilizam os principais recursos e benefícios do sistema do módulo atuante.', 'Concluído', '2026-01-31', NULL),
  ('São José da Coroa Grande', 'PE', 2026, 1, 'Acompanhar as integrações, quando aplicável.', 'Concluído', '2026-01-31', NULL),
  ('São José da Coroa Grande', 'PE', 2026, 1, 'Monitorar a necessidade de treinamentos e atualizações.', 'Concluído', '2026-01-31', NULL),
  ('São José da Coroa Grande', 'PE', 2026, 1, 'Informar ao cliente sobre as principais implementações do módulo.', 'Concluído', '2026-01-31', NULL),
  ('São José da Coroa Grande', 'PE', 2026, 1, 'Acompanhar e gerenciar as demandas de programação e/ou técnicas.', 'Concluído', '2026-01-31', NULL),
  ('São José da Coroa Grande', 'PE', 2026, 1, 'No portal da transparência, acompanhar mensalmente as pendências, encaminhá-las ao responsável e enviar o Integra por e-mail.', 'Concluído', '2026-01-31', NULL),
  ('São José da Coroa Grande', 'PE', 2026, 2, 'Monitorar a alimentação do sistema pelo cliente, verificando possível ausência ou má alimentação.', 'Concluído', '2026-02-28', NULL),
  ('São José da Coroa Grande', 'PE', 2026, 2, 'Verificar se os clientes utilizam os principais recursos e benefícios do sistema do módulo atuante.', 'Concluído', '2026-02-28', NULL),
  ('São José da Coroa Grande', 'PE', 2026, 2, 'Acompanhar as integrações, quando aplicável.', 'Concluído', '2026-02-28', NULL),
  ('São José da Coroa Grande', 'PE', 2026, 2, 'Monitorar a necessidade de treinamentos e atualizações.', 'Concluído', '2026-02-28', NULL),
  ('São José da Coroa Grande', 'PE', 2026, 2, 'Informar ao cliente sobre as principais implementações do módulo.', 'Concluído', '2026-02-28', NULL),
  ('São José da Coroa Grande', 'PE', 2026, 2, 'Acompanhar e gerenciar as demandas de programação e/ou técnicas.', 'Concluído', '2026-02-28', NULL),
  ('São José da Coroa Grande', 'PE', 2026, 2, 'No portal da transparência, acompanhar mensalmente as pendências, encaminhá-las ao responsável e enviar o Integra por e-mail.', 'Concluído', '2026-02-28', NULL),
  ('São José da Coroa Grande', 'PE', 2026, 3, 'Monitorar a alimentação do sistema pelo cliente, verificando possível ausência ou má alimentação.', 'Concluído', '2026-03-31', NULL),
  ('São José da Coroa Grande', 'PE', 2026, 3, 'Verificar se os clientes utilizam os principais recursos e benefícios do sistema do módulo atuante.', 'Concluído', '2026-03-31', NULL),
  ('São José da Coroa Grande', 'PE', 2026, 3, 'Acompanhar as integrações, quando aplicável.', 'Concluído', '2026-03-31', NULL),
  ('São José da Coroa Grande', 'PE', 2026, 3, 'Monitorar a necessidade de treinamentos e atualizações.', 'Concluído', '2026-03-31', NULL),
  ('São José da Coroa Grande', 'PE', 2026, 3, 'Informar ao cliente sobre as principais implementações do módulo.', 'Concluído', '2026-03-31', NULL),
  ('São José da Coroa Grande', 'PE', 2026, 3, 'Acompanhar e gerenciar as demandas de programação e/ou técnicas.', 'Concluído', '2026-03-31', NULL),
  ('São José da Coroa Grande', 'PE', 2026, 3, 'No portal da transparência, acompanhar mensalmente as pendências, encaminhá-las ao responsável e enviar o Integra por e-mail.', 'Concluído', '2026-03-31', NULL),
  ('São José da Coroa Grande', 'PE', 2026, 4, 'Monitorar a alimentação do sistema pelo cliente, verificando possível ausência ou má alimentação.', 'Concluído', '2026-04-30', NULL),
  ('São José da Coroa Grande', 'PE', 2026, 4, 'Verificar se os clientes utilizam os principais recursos e benefícios do sistema do módulo atuante.', 'Concluído', '2026-04-30', NULL),
  ('São José da Coroa Grande', 'PE', 2026, 4, 'Acompanhar as integrações, quando aplicável.', 'Concluído', '2026-04-30', NULL),
  ('São José da Coroa Grande', 'PE', 2026, 4, 'Monitorar a necessidade de treinamentos e atualizações.', 'Concluído', '2026-04-30', NULL),
  ('São José da Coroa Grande', 'PE', 2026, 4, 'Informar ao cliente sobre as principais implementações do módulo.', 'Concluído', '2026-04-30', NULL),
  ('São José da Coroa Grande', 'PE', 2026, 4, 'Acompanhar e gerenciar as demandas de programação e/ou técnicas.', 'Concluído', '2026-04-30', NULL),
  ('São José da Coroa Grande', 'PE', 2026, 4, 'No portal da transparência, acompanhar mensalmente as pendências, encaminhá-las ao responsável e enviar o Integra por e-mail.', 'Concluído', '2026-04-30', NULL),
  ('São José da Coroa Grande', 'PE', 2026, 5, 'Monitorar a alimentação do sistema pelo cliente, verificando possível ausência ou má alimentação.', 'Concluído', '2026-05-31', NULL),
  ('São José da Coroa Grande', 'PE', 2026, 5, 'Verificar se os clientes utilizam os principais recursos e benefícios do sistema do módulo atuante.', 'Concluído', '2026-05-31', NULL),
  ('São José da Coroa Grande', 'PE', 2026, 5, 'Acompanhar as integrações, quando aplicável.', 'Concluído', '2026-05-31', NULL),
  ('São José da Coroa Grande', 'PE', 2026, 5, 'Monitorar a necessidade de treinamentos e atualizações.', 'Concluído', '2026-05-31', NULL),
  ('São José da Coroa Grande', 'PE', 2026, 5, 'Informar ao cliente sobre as principais implementações do módulo.', 'Concluído', '2026-05-31', NULL),
  ('São José da Coroa Grande', 'PE', 2026, 5, 'Acompanhar e gerenciar as demandas de programação e/ou técnicas.', 'Concluído', '2026-05-31', NULL),
  ('São José da Coroa Grande', 'PE', 2026, 5, 'No portal da transparência, acompanhar mensalmente as pendências, encaminhá-las ao responsável e enviar o Integra por e-mail.', 'Concluído', '2026-05-31', NULL),
  ('São José da Coroa Grande', 'PE', 2026, 6, 'Monitorar a alimentação do sistema pelo cliente, verificando possível ausência ou má alimentação.', 'Concluído', '2026-06-30', NULL),
  ('São José da Coroa Grande', 'PE', 2026, 6, 'Verificar se os clientes utilizam os principais recursos e benefícios do sistema do módulo atuante.', 'Concluído', '2026-06-30', NULL),
  ('São José da Coroa Grande', 'PE', 2026, 6, 'Acompanhar as integrações, quando aplicável.', 'Concluído', '2026-06-30', NULL),
  ('São José da Coroa Grande', 'PE', 2026, 6, 'Monitorar a necessidade de treinamentos e atualizações.', 'Concluído', '2026-06-30', NULL),
  ('São José da Coroa Grande', 'PE', 2026, 6, 'Informar ao cliente sobre as principais implementações do módulo.', 'Concluído', '2026-06-30', NULL),
  ('São José da Coroa Grande', 'PE', 2026, 6, 'Acompanhar e gerenciar as demandas de programação e/ou técnicas.', 'Concluído', '2026-06-30', NULL),
  ('São José da Coroa Grande', 'PE', 2026, 6, 'No portal da transparência, acompanhar mensalmente as pendências, encaminhá-las ao responsável e enviar o Integra por e-mail.', 'Concluído', '2026-07-31', NULL),
  ('São José da Coroa Grande', 'PE', 2026, 7, 'Monitorar a alimentação do sistema pelo cliente, verificando possível ausência ou má alimentação.', 'Concluído', '2026-07-31', NULL),
  ('São José da Coroa Grande', 'PE', 2026, 7, 'Verificar se os clientes utilizam os principais recursos e benefícios do sistema do módulo atuante.', 'Concluído', '2026-07-31', NULL),
  ('São José da Coroa Grande', 'PE', 2026, 7, 'Acompanhar as integrações, quando aplicável.', 'Concluído', '2026-07-31', NULL),
  ('São José da Coroa Grande', 'PE', 2026, 7, 'Monitorar a necessidade de treinamentos e atualizações.', 'Concluído', '2026-07-31', NULL),
  ('São José da Coroa Grande', 'PE', 2026, 7, 'Informar ao cliente sobre as principais implementações do módulo.', 'Concluído', '2026-07-31', NULL),
  ('São José da Coroa Grande', 'PE', 2026, 7, 'Acompanhar e gerenciar as demandas de programação e/ou técnicas.', 'Concluído', '2026-07-31', NULL),
  ('São José da Coroa Grande', 'PE', 2026, 7, 'No portal da transparência, acompanhar mensalmente as pendências, encaminhá-las ao responsável e enviar o Integra por e-mail.', 'Concluído', '2026-07-31', NULL),
  ('São José da Coroa Grande', 'PE', 2026, 8, 'Monitorar a alimentação do sistema pelo cliente, verificando possível ausência ou má alimentação.', 'Pendente', '1899-12-30', NULL),
  ('São José da Coroa Grande', 'PE', 2026, 8, 'Verificar se os clientes utilizam os principais recursos e benefícios do sistema do módulo atuante.', 'Pendente', '1899-12-30', NULL),
  ('São José da Coroa Grande', 'PE', 2026, 8, 'Acompanhar as integrações, quando aplicável.', 'Pendente', '1899-12-30', NULL),
  ('São José da Coroa Grande', 'PE', 2026, 8, 'Monitorar a necessidade de treinamentos e atualizações.', 'Pendente', '1899-12-30', NULL),
  ('São José da Coroa Grande', 'PE', 2026, 8, 'Informar ao cliente sobre as principais implementações do módulo.', 'Pendente', '1899-12-30', NULL),
  ('São José da Coroa Grande', 'PE', 2026, 8, 'Acompanhar e gerenciar as demandas de programação e/ou técnicas.', 'Pendente', '1899-12-30', NULL),
  ('São José da Coroa Grande', 'PE', 2026, 8, 'No portal da transparência, acompanhar mensalmente as pendências, encaminhá-las ao responsável e enviar o Integra por e-mail.', 'Pendente', '1899-12-30', NULL),
  ('São José da Coroa Grande', 'PE', 2026, 9, 'Monitorar a alimentação do sistema pelo cliente, verificando possível ausência ou má alimentação.', 'Pendente', '1899-12-30', NULL),
  ('São José da Coroa Grande', 'PE', 2026, 9, 'Verificar se os clientes utilizam os principais recursos e benefícios do sistema do módulo atuante.', 'Pendente', '1899-12-30', NULL),
  ('São José da Coroa Grande', 'PE', 2026, 9, 'Acompanhar as integrações, quando aplicável.', 'Pendente', '1899-12-30', NULL),
  ('São José da Coroa Grande', 'PE', 2026, 9, 'Monitorar a necessidade de treinamentos e atualizações.', 'Pendente', '1899-12-30', NULL),
  ('São José da Coroa Grande', 'PE', 2026, 9, 'Informar ao cliente sobre as principais implementações do módulo.', 'Pendente', '1899-12-30', NULL),
  ('São José da Coroa Grande', 'PE', 2026, 9, 'Acompanhar e gerenciar as demandas de programação e/ou técnicas.', 'Pendente', '1899-12-30', NULL),
  ('São José da Coroa Grande', 'PE', 2026, 9, 'No portal da transparência, acompanhar mensalmente as pendências, encaminhá-las ao responsável e enviar o Integra por e-mail.', 'Pendente', '1899-12-30', NULL),
  ('São José da Coroa Grande', 'PE', 2026, 10, 'Monitorar a alimentação do sistema pelo cliente, verificando possível ausência ou má alimentação.', 'Pendente', '1899-12-30', NULL),
  ('São José da Coroa Grande', 'PE', 2026, 10, 'Verificar se os clientes utilizam os principais recursos e benefícios do sistema do módulo atuante.', 'Pendente', '1899-12-30', NULL),
  ('São José da Coroa Grande', 'PE', 2026, 10, 'Acompanhar as integrações, quando aplicável.', 'Pendente', '1899-12-30', NULL),
  ('São José da Coroa Grande', 'PE', 2026, 10, 'Monitorar a necessidade de treinamentos e atualizações.', 'Pendente', '1899-12-30', NULL),
  ('São José da Coroa Grande', 'PE', 2026, 10, 'Informar ao cliente sobre as principais implementações do módulo.', 'Pendente', '1899-12-30', NULL),
  ('São José da Coroa Grande', 'PE', 2026, 10, 'Acompanhar e gerenciar as demandas de programação e/ou técnicas.', 'Pendente', '1899-12-30', NULL),
  ('São José da Coroa Grande', 'PE', 2026, 10, 'No portal da transparência, acompanhar mensalmente as pendências, encaminhá-las ao responsável e enviar o Integra por e-mail.', 'Pendente', '1899-12-30', NULL),
  ('São José da Coroa Grande', 'PE', 2026, 11, 'Monitorar a alimentação do sistema pelo cliente, verificando possível ausência ou má alimentação.', 'Pendente', '1899-12-30', NULL),
  ('São José da Coroa Grande', 'PE', 2026, 11, 'Verificar se os clientes utilizam os principais recursos e benefícios do sistema do módulo atuante.', 'Pendente', '1899-12-30', NULL),
  ('São José da Coroa Grande', 'PE', 2026, 11, 'Acompanhar as integrações, quando aplicável.', 'Pendente', '1899-12-30', NULL),
  ('São José da Coroa Grande', 'PE', 2026, 11, 'Monitorar a necessidade de treinamentos e atualizações.', 'Pendente', '1899-12-30', NULL),
  ('São José da Coroa Grande', 'PE', 2026, 11, 'Informar ao cliente sobre as principais implementações do módulo.', 'Pendente', '1899-12-30', NULL),
  ('São José da Coroa Grande', 'PE', 2026, 11, 'Acompanhar e gerenciar as demandas de programação e/ou técnicas.', 'Pendente', '1899-12-30', NULL),
  ('São José da Coroa Grande', 'PE', 2026, 11, 'No portal da transparência, acompanhar mensalmente as pendências, encaminhá-las ao responsável e enviar o Integra por e-mail.', 'Pendente', '1899-12-30', NULL),
  ('São José da Coroa Grande', 'PE', 2026, 12, 'Monitorar a alimentação do sistema pelo cliente, verificando possível ausência ou má alimentação.', 'Pendente', '1899-12-30', NULL),
  ('São José da Coroa Grande', 'PE', 2026, 12, 'Verificar se os clientes utilizam os principais recursos e benefícios do sistema do módulo atuante.', 'Pendente', '1899-12-30', NULL),
  ('São José da Coroa Grande', 'PE', 2026, 12, 'Acompanhar as integrações, quando aplicável.', 'Pendente', '1899-12-30', NULL),
  ('São José da Coroa Grande', 'PE', 2026, 12, 'Monitorar a necessidade de treinamentos e atualizações.', 'Pendente', '1899-12-30', NULL),
  ('São José da Coroa Grande', 'PE', 2026, 12, 'Informar ao cliente sobre as principais implementações do módulo.', 'Pendente', '1899-12-30', NULL),
  ('São José da Coroa Grande', 'PE', 2026, 12, 'Acompanhar e gerenciar as demandas de programação e/ou técnicas.', 'Pendente', '1899-12-30', NULL),
  ('São José da Coroa Grande', 'PE', 2026, 12, 'No portal da transparência, acompanhar mensalmente as pendências, encaminhá-las ao responsável e enviar o Integra por e-mail.', 'Pendente', '1899-12-30', NULL),
  ('Tacaratu', 'PE', 2026, 1, 'Monitorar a alimentação do sistema pelo cliente, verificando possível ausência ou má alimentação.', 'Concluído', '2026-01-31', NULL),
  ('Tacaratu', 'PE', 2026, 1, 'Verificar se os clientes utilizam os principais recursos e benefícios do sistema do módulo atuante.', 'Concluído', '2026-01-31', NULL),
  ('Tacaratu', 'PE', 2026, 1, 'Acompanhar as integrações, quando aplicável.', 'Concluído', '2026-01-31', NULL),
  ('Tacaratu', 'PE', 2026, 1, 'Monitorar a necessidade de treinamentos e atualizações.', 'Concluído', '2026-01-31', NULL),
  ('Tacaratu', 'PE', 2026, 1, 'Informar ao cliente sobre as principais implementações do módulo.', 'Concluído', '2026-01-31', NULL),
  ('Tacaratu', 'PE', 2026, 1, 'Acompanhar e gerenciar as demandas de programação e/ou técnicas.', 'Concluído', '2026-01-31', NULL),
  ('Tacaratu', 'PE', 2026, 1, 'No portal da transparência, acompanhar mensalmente as pendências, encaminhá-las ao responsável e enviar o Integra por e-mail.', 'Concluído', '2026-01-31', NULL),
  ('Tacaratu', 'PE', 2026, 2, 'Monitorar a alimentação do sistema pelo cliente, verificando possível ausência ou má alimentação.', 'Concluído', '2026-02-28', NULL),
  ('Tacaratu', 'PE', 2026, 2, 'Verificar se os clientes utilizam os principais recursos e benefícios do sistema do módulo atuante.', 'Concluído', '2026-02-28', NULL),
  ('Tacaratu', 'PE', 2026, 2, 'Acompanhar as integrações, quando aplicável.', 'Concluído', '2026-02-28', NULL),
  ('Tacaratu', 'PE', 2026, 2, 'Monitorar a necessidade de treinamentos e atualizações.', 'Concluído', '2026-02-28', NULL),
  ('Tacaratu', 'PE', 2026, 2, 'Informar ao cliente sobre as principais implementações do módulo.', 'Concluído', '2026-02-28', NULL),
  ('Tacaratu', 'PE', 2026, 2, 'Acompanhar e gerenciar as demandas de programação e/ou técnicas.', 'Concluído', '2026-02-28', NULL),
  ('Tacaratu', 'PE', 2026, 2, 'No portal da transparência, acompanhar mensalmente as pendências, encaminhá-las ao responsável e enviar o Integra por e-mail.', 'Concluído', '2026-02-28', NULL),
  ('Tacaratu', 'PE', 2026, 3, 'Monitorar a alimentação do sistema pelo cliente, verificando possível ausência ou má alimentação.', 'Concluído', '2026-03-31', NULL),
  ('Tacaratu', 'PE', 2026, 3, 'Verificar se os clientes utilizam os principais recursos e benefícios do sistema do módulo atuante.', 'Concluído', '2026-03-31', NULL),
  ('Tacaratu', 'PE', 2026, 3, 'Acompanhar as integrações, quando aplicável.', 'Concluído', '2026-03-31', NULL),
  ('Tacaratu', 'PE', 2026, 3, 'Monitorar a necessidade de treinamentos e atualizações.', 'Concluído', '2026-03-31', NULL),
  ('Tacaratu', 'PE', 2026, 3, 'Informar ao cliente sobre as principais implementações do módulo.', 'Concluído', '2026-03-31', NULL),
  ('Tacaratu', 'PE', 2026, 3, 'Acompanhar e gerenciar as demandas de programação e/ou técnicas.', 'Concluído', '2026-03-31', NULL),
  ('Tacaratu', 'PE', 2026, 3, 'No portal da transparência, acompanhar mensalmente as pendências, encaminhá-las ao responsável e enviar o Integra por e-mail.', 'Concluído', '2026-03-31', NULL),
  ('Tacaratu', 'PE', 2026, 4, 'Monitorar a alimentação do sistema pelo cliente, verificando possível ausência ou má alimentação.', 'Concluído', '2026-04-30', NULL),
  ('Tacaratu', 'PE', 2026, 4, 'Verificar se os clientes utilizam os principais recursos e benefícios do sistema do módulo atuante.', 'Concluído', '2026-04-30', NULL),
  ('Tacaratu', 'PE', 2026, 4, 'Acompanhar as integrações, quando aplicável.', 'Concluído', '2026-04-30', NULL),
  ('Tacaratu', 'PE', 2026, 4, 'Monitorar a necessidade de treinamentos e atualizações.', 'Concluído', '2026-04-30', NULL),
  ('Tacaratu', 'PE', 2026, 4, 'Informar ao cliente sobre as principais implementações do módulo.', 'Concluído', '2026-04-30', NULL),
  ('Tacaratu', 'PE', 2026, 4, 'Acompanhar e gerenciar as demandas de programação e/ou técnicas.', 'Concluído', '2026-04-30', NULL),
  ('Tacaratu', 'PE', 2026, 4, 'No portal da transparência, acompanhar mensalmente as pendências, encaminhá-las ao responsável e enviar o Integra por e-mail.', 'Concluído', '2026-04-30', NULL),
  ('Tacaratu', 'PE', 2026, 5, 'Monitorar a alimentação do sistema pelo cliente, verificando possível ausência ou má alimentação.', 'Concluído', '2026-05-31', NULL),
  ('Tacaratu', 'PE', 2026, 5, 'Verificar se os clientes utilizam os principais recursos e benefícios do sistema do módulo atuante.', 'Concluído', '2026-05-31', NULL),
  ('Tacaratu', 'PE', 2026, 5, 'Acompanhar as integrações, quando aplicável.', 'Concluído', '2026-05-31', NULL),
  ('Tacaratu', 'PE', 2026, 5, 'Monitorar a necessidade de treinamentos e atualizações.', 'Concluído', '2026-05-31', NULL),
  ('Tacaratu', 'PE', 2026, 5, 'Informar ao cliente sobre as principais implementações do módulo.', 'Concluído', '2026-05-31', NULL),
  ('Tacaratu', 'PE', 2026, 5, 'Acompanhar e gerenciar as demandas de programação e/ou técnicas.', 'Concluído', '2026-05-31', NULL),
  ('Tacaratu', 'PE', 2026, 5, 'No portal da transparência, acompanhar mensalmente as pendências, encaminhá-las ao responsável e enviar o Integra por e-mail.', 'Concluído', '2026-05-31', NULL),
  ('Tacaratu', 'PE', 2026, 6, 'Monitorar a alimentação do sistema pelo cliente, verificando possível ausência ou má alimentação.', 'Concluído', '2026-06-30', NULL),
  ('Tacaratu', 'PE', 2026, 6, 'Verificar se os clientes utilizam os principais recursos e benefícios do sistema do módulo atuante.', 'Concluído', '2026-06-30', NULL),
  ('Tacaratu', 'PE', 2026, 6, 'Acompanhar as integrações, quando aplicável.', 'Concluído', '2026-06-30', NULL),
  ('Tacaratu', 'PE', 2026, 6, 'Monitorar a necessidade de treinamentos e atualizações.', 'Concluído', '2026-06-30', NULL),
  ('Tacaratu', 'PE', 2026, 6, 'Informar ao cliente sobre as principais implementações do módulo.', 'Concluído', '2026-06-30', NULL),
  ('Tacaratu', 'PE', 2026, 6, 'Acompanhar e gerenciar as demandas de programação e/ou técnicas.', 'Concluído', '2026-06-30', NULL),
  ('Tacaratu', 'PE', 2026, 6, 'No portal da transparência, acompanhar mensalmente as pendências, encaminhá-las ao responsável e enviar o Integra por e-mail.', 'Concluído', '2026-07-31', NULL),
  ('Tacaratu', 'PE', 2026, 7, 'Monitorar a alimentação do sistema pelo cliente, verificando possível ausência ou má alimentação.', 'Concluído', '2026-07-31', NULL),
  ('Tacaratu', 'PE', 2026, 7, 'Verificar se os clientes utilizam os principais recursos e benefícios do sistema do módulo atuante.', 'Concluído', '2026-07-31', NULL),
  ('Tacaratu', 'PE', 2026, 7, 'Acompanhar as integrações, quando aplicável.', 'Concluído', '2026-07-31', NULL),
  ('Tacaratu', 'PE', 2026, 7, 'Monitorar a necessidade de treinamentos e atualizações.', 'Concluído', '2026-07-31', NULL),
  ('Tacaratu', 'PE', 2026, 7, 'Informar ao cliente sobre as principais implementações do módulo.', 'Concluído', '2026-07-31', NULL),
  ('Tacaratu', 'PE', 2026, 7, 'Acompanhar e gerenciar as demandas de programação e/ou técnicas.', 'Concluído', '2026-07-31', NULL),
  ('Tacaratu', 'PE', 2026, 7, 'No portal da transparência, acompanhar mensalmente as pendências, encaminhá-las ao responsável e enviar o Integra por e-mail.', 'Concluído', '2026-07-31', NULL),
  ('Tacaratu', 'PE', 2026, 8, 'Monitorar a alimentação do sistema pelo cliente, verificando possível ausência ou má alimentação.', 'Pendente', '1899-12-30', NULL),
  ('Tacaratu', 'PE', 2026, 8, 'Verificar se os clientes utilizam os principais recursos e benefícios do sistema do módulo atuante.', 'Pendente', '1899-12-30', NULL),
  ('Tacaratu', 'PE', 2026, 8, 'Acompanhar as integrações, quando aplicável.', 'Pendente', '1899-12-30', NULL),
  ('Tacaratu', 'PE', 2026, 8, 'Monitorar a necessidade de treinamentos e atualizações.', 'Pendente', '1899-12-30', NULL),
  ('Tacaratu', 'PE', 2026, 8, 'Informar ao cliente sobre as principais implementações do módulo.', 'Pendente', '1899-12-30', NULL),
  ('Tacaratu', 'PE', 2026, 8, 'Acompanhar e gerenciar as demandas de programação e/ou técnicas.', 'Pendente', '1899-12-30', NULL),
  ('Tacaratu', 'PE', 2026, 8, 'No portal da transparência, acompanhar mensalmente as pendências, encaminhá-las ao responsável e enviar o Integra por e-mail.', 'Pendente', '1899-12-30', NULL),
  ('Tacaratu', 'PE', 2026, 9, 'Monitorar a alimentação do sistema pelo cliente, verificando possível ausência ou má alimentação.', 'Pendente', '1899-12-30', NULL),
  ('Tacaratu', 'PE', 2026, 9, 'Verificar se os clientes utilizam os principais recursos e benefícios do sistema do módulo atuante.', 'Pendente', '1899-12-30', NULL),
  ('Tacaratu', 'PE', 2026, 9, 'Acompanhar as integrações, quando aplicável.', 'Pendente', '1899-12-30', NULL),
  ('Tacaratu', 'PE', 2026, 9, 'Monitorar a necessidade de treinamentos e atualizações.', 'Pendente', '1899-12-30', NULL),
  ('Tacaratu', 'PE', 2026, 9, 'Informar ao cliente sobre as principais implementações do módulo.', 'Pendente', '1899-12-30', NULL),
  ('Tacaratu', 'PE', 2026, 9, 'Acompanhar e gerenciar as demandas de programação e/ou técnicas.', 'Pendente', '1899-12-30', NULL),
  ('Tacaratu', 'PE', 2026, 9, 'No portal da transparência, acompanhar mensalmente as pendências, encaminhá-las ao responsável e enviar o Integra por e-mail.', 'Pendente', '1899-12-30', NULL),
  ('Tacaratu', 'PE', 2026, 10, 'Monitorar a alimentação do sistema pelo cliente, verificando possível ausência ou má alimentação.', 'Pendente', '1899-12-30', NULL),
  ('Tacaratu', 'PE', 2026, 10, 'Verificar se os clientes utilizam os principais recursos e benefícios do sistema do módulo atuante.', 'Pendente', '1899-12-30', NULL),
  ('Tacaratu', 'PE', 2026, 10, 'Acompanhar as integrações, quando aplicável.', 'Pendente', '1899-12-30', NULL),
  ('Tacaratu', 'PE', 2026, 10, 'Monitorar a necessidade de treinamentos e atualizações.', 'Pendente', '1899-12-30', NULL),
  ('Tacaratu', 'PE', 2026, 10, 'Informar ao cliente sobre as principais implementações do módulo.', 'Pendente', '1899-12-30', NULL),
  ('Tacaratu', 'PE', 2026, 10, 'Acompanhar e gerenciar as demandas de programação e/ou técnicas.', 'Pendente', '1899-12-30', NULL),
  ('Tacaratu', 'PE', 2026, 10, 'No portal da transparência, acompanhar mensalmente as pendências, encaminhá-las ao responsável e enviar o Integra por e-mail.', 'Pendente', '1899-12-30', NULL),
  ('Tacaratu', 'PE', 2026, 11, 'Monitorar a alimentação do sistema pelo cliente, verificando possível ausência ou má alimentação.', 'Pendente', '1899-12-30', NULL),
  ('Tacaratu', 'PE', 2026, 11, 'Verificar se os clientes utilizam os principais recursos e benefícios do sistema do módulo atuante.', 'Pendente', '1899-12-30', NULL),
  ('Tacaratu', 'PE', 2026, 11, 'Acompanhar as integrações, quando aplicável.', 'Pendente', '1899-12-30', NULL),
  ('Tacaratu', 'PE', 2026, 11, 'Monitorar a necessidade de treinamentos e atualizações.', 'Pendente', '1899-12-30', NULL),
  ('Tacaratu', 'PE', 2026, 11, 'Informar ao cliente sobre as principais implementações do módulo.', 'Pendente', '1899-12-30', NULL),
  ('Tacaratu', 'PE', 2026, 11, 'Acompanhar e gerenciar as demandas de programação e/ou técnicas.', 'Pendente', '1899-12-30', NULL),
  ('Tacaratu', 'PE', 2026, 11, 'No portal da transparência, acompanhar mensalmente as pendências, encaminhá-las ao responsável e enviar o Integra por e-mail.', 'Pendente', '1899-12-30', NULL),
  ('Tacaratu', 'PE', 2026, 12, 'Monitorar a alimentação do sistema pelo cliente, verificando possível ausência ou má alimentação.', 'Pendente', '1899-12-30', NULL),
  ('Tacaratu', 'PE', 2026, 12, 'Verificar se os clientes utilizam os principais recursos e benefícios do sistema do módulo atuante.', 'Pendente', '1899-12-30', NULL),
  ('Tacaratu', 'PE', 2026, 12, 'Acompanhar as integrações, quando aplicável.', 'Pendente', '1899-12-30', NULL),
  ('Tacaratu', 'PE', 2026, 12, 'Monitorar a necessidade de treinamentos e atualizações.', 'Pendente', '1899-12-30', NULL),
  ('Tacaratu', 'PE', 2026, 12, 'Informar ao cliente sobre as principais implementações do módulo.', 'Pendente', '1899-12-30', NULL),
  ('Tacaratu', 'PE', 2026, 12, 'Acompanhar e gerenciar as demandas de programação e/ou técnicas.', 'Pendente', '1899-12-30', NULL),
  ('Tacaratu', 'PE', 2026, 12, 'No portal da transparência, acompanhar mensalmente as pendências, encaminhá-las ao responsável e enviar o Integra por e-mail.', 'Pendente', '1899-12-30', NULL)
ON CONFLICT (municipio, uf, ano, mes, atividade)
DO UPDATE SET
  status_origem = EXCLUDED.status_origem,
  data_conclusao = EXCLUDED.data_conclusao,
  observacoes = EXCLUDED.observacoes;

COMMIT;

-- Estas linhas ficam em área de conciliação até que módulo e responsável sejam confirmados.
SELECT municipio, uf, COUNT(*) AS itens
FROM checklist_legado_importacao
WHERE responsabilidade_id IS NULL
GROUP BY municipio, uf
ORDER BY municipio;
